In [1]:
import pandas as pd
import numpy as np
from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import pipeline
from tqdm.auto import tqdm
from torch.utils.data import Dataset, DataLoader
import jsonlines
import itertools

In [4]:
NER = ["STRAIN"]

In [5]:
l = []
for ner in NER:
	test_sentences = pd.read_json(f"../NER/{ner}/test.json", lines=True)
	test_output = pd.read_json(f"../NER_output/{ner}/test_outputs.json")
	merged = pd.merge(test_sentences, test_output, left_index=True, right_index=True)
	merged.loc[:,"ner"] = ner
	l.append(merged)

df = pd.concat(l)

In [6]:
df = df.reset_index().drop(columns=["index"])

In [7]:
df

,tokens,ner_tags,id,predictions,label_ids,word_ids,ner
0,"[In, the, previously, studied, Desulfovibrio, ...","[O, O, O, O, B, I, I, O, O, O, O, O, O, O, O, ...",0,"[[-2.474609375, -2.5703125, 5.10546875], [-2.7...","[-100, 2, 2, 2, 2, 0, -100, -100, -100, 1, 1, ...","[None, 0, 1, 2, 3, 4, 4, 4, 4, 5, 6, 6, 6, 6, ...",STRAIN
1,"[The, present, study, aims, at, the, thorough,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",1,"[[-2.4296875, -2.150390625, 4.390625], [-2.818...","[-100, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1...",STRAIN
2,"[In, contrast, ,, D., alkenigignens, IP3, 3^T,...","[O, O, O, B, I, I, I, O, O, O, O, O, O, O, O, ...",2,"[[-2.744140625, -2.302734375, 4.69140625], [-2...","[-100, 2, 2, 2, 0, -100, 1, -100, -100, -100, ...","[None, 0, 1, 2, 3, 3, 4, 4, 4, 4, 4, 5, 6, 6, ...",STRAIN
3,"[These, include, a, ~22.1, kb, region, contain...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",3,"[[-2.56640625, -2.955078125, 5.484375], [-3.0,...","[-100, 2, 2, 2, 2, -100, -100, -100, 2, 2, 2, ...","[None, 0, 1, 2, 3, 3, 3, 3, 4, 5, 6, 7, 8, 9, ...",STRAIN
4,"[Erwinia, carotovora, subsp., carotovora, is, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",4,"[[-2.66015625, -2.583984375, 5.1484375], [0.53...","[-100, 2, -100, -100, 2, -100, -100, -100, 2, ...","[None, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, ...",STRAIN
...,...,...,...,...,...,...,...
493,"[Phaseolibacter, flectensATCC, 12775^T, (, =, ...","[B, I, I, O, O, B, I, O, B, I, O, B, I, O, B, ...",493,"[[-2.169921875, -1.9990234375, 4.1171875], [3....","[-100, 0, -100, -100, -100, -100, 1, -100, -10...","[None, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, ...",STRAIN
494,"[Pellets, were, re, suspended, in, 100, μL, of...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",494,"[[-2.60546875, -2.88671875, 5.3515625], [-2.70...","[-100, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, -100, 2, ...","[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 10, 11...",STRAIN
495,"[The, experiments, were, conducted, with, the,...","[O, O, O, O, O, O, O, B, I, I, O, B, I, O, O, O]",495,"[[-1.9150390625, -0.81591796875, 2.509765625],...","[-100, 2, 2, 2, 2, 2, 2, 2, 0, -100, 1, -100, ...","[None, 0, 1, 2, 3, 4, 5, 6, 7, 7, 8, 8, 8, 8, ...",STRAIN
496,"[To, date, ,, few, strains, have, been, report...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",496,"[[-2.21875, -2.9140625, 5.05859375], [-2.80664...","[-100, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, -100, ...","[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 1...",STRAIN
497,"[Immediately, a, reference, sequence, had, bee...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",497,"[[-2.447265625, -2.8125, 5.22265625], [-2.8164...","[-100, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, -10...","[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1...",STRAIN

In [8]:
label_ids = df[["label_ids"]]

In [9]:
annotations = []
current_annotation = None

for j in range(len(df)):
	for i in zip(df.loc[j, "tokens"], df.loc[j, "ner_tags"]):
		if i[1] != "O":
			if current_annotation is None:
				current_annotation = { "text": i[0]}
			else:
				current_annotation["text"] += " " + i[0]
		else:
			if current_annotation is not None:
				annotations.append(current_annotation)
				current_annotation = None

if current_annotation is not None:
	annotations.append(current_annotation)

### Predict sentences again

In [10]:
ner = "STRAIN"

In [11]:
path= f"../NER_output/{ner}"

tokenizer = AutoTokenizer.from_pretrained(path, model_max_length=512)
model = AutoModelForTokenClassification.from_pretrained(path)

nlp = pipeline(task='ner', model=model, tokenizer=tokenizer,
               aggregation_strategy="average", device=0)

In [12]:
# Specify the path to the JSONL file
jsonl_file = f"../NER/{ner}/test.jsonls"

predictions = []
# Open the JSONL file
with jsonlines.open(jsonl_file) as reader:
    # Iterate over each line in the file
    for line in reader:
        for l in line:
            # Get the value from the "text" field
            text = l["data"]["text"]
            # Pass the value to the nlp() function
            print(text)
            predict = nlp(text)
            predictions.append(predict)
            print(predict)

In the previously studied Desulfovibrio vulgaris Hildenborough cytochrome c_3, the four iron ions are at the vertices of a deformed tetrahedron [25,26], whereas in the presently studied Shewanella oneidensis MR 1 Small Tetraheme Cytochrome (STC), the irons form approximately the pattern of a hockey stick (a ‘dog leg’ according to others [29]), with some of the Fe Fe distances significantly longer than in the cytochrome c_3 structure [27].

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

[{'entity_group': 'I', 'score': 0.7429821, 'word': 'desulfovibrio vulgaris hildenborough', 'start': 26, 'end': 62}, {'entity_group': 'B', 'score': 0.61041486, 'word': 'shewanella', 'start': 186, 'end': 196}, {'entity_group': 'I', 'score': 0.97677726, 'word': 'oneidensis mr 1', 'start': 197, 'end': 212}]
The present study aims at the thorough elucidation of the plant growth promoting traits and to identify other metabolic features of B. aryabhattai AB211, rhizobacteria isolated from tea rhizosphere.
[{'entity_group': 'B', 'score': 0.9834554, 'word': 'b', 'start': 132, 'end': 133}, {'entity_group': 'I', 'score': 0.9816315, 'word': '. aryabhattai ab211', 'start': 133, 'end': 152}]
In contrast, D. alkenigignens IP3 3^T concurrently dechlorinated 1,2 dichloroethane and 1,2 dichloropropane over a comparably large concentration range [3].
[{'entity_group': 'B', 'score': 0.9871869, 'word': 'd', 'start': 13, 'end': 14}, {'entity_group': 'I', 'score': 0.9762908, 'word': '. alkenigignens ip3 3', 'start': 14, 'end': 35}, {'entity_group': 'I', 'score': 0.52383447, 'word': 't', 'start': 36, 'end': 37}]
These include a ~22.1 kb region containing two phosphate associated operons, with one containing a phosphate transporter system pstS, pstC, pstA, pstB and the other containing genes to control phosphate transport, i.e. phoU, phoB and phoR ( Fig 4A and S4 Table ) together with a proceeding methyl accepting chemotaxis protein.
[]
Erwinia carotovora subsp. carotovora is one of the most destructive plant pathogen bacteria [6], as the bacterium strain causes bacterial soft rot in potatoes and other crops [7].
[]
However, in BS1 another homologous czc determinant was identified on the chromid, most similar to the czc determinant from pMOL30 in CH34.
[]
In addition, our results demonstrated the sensitivity of AM1 ITA production to culture conditions, suggesting further process engineering is required to optimize ITA production in scaled up bioreactors.
[]
The type strain, Sr59 ^T (=CGMCC 1.9254 ^T = NBRC 114035 ^T ), was isolated from the ice sample obtained from the supraglacial zone of No. 1 glacier in Xinjiang Uygur Autonomous Region, China.
[{'entity_group': 'B', 'score': 0.5020678, 'word': 'sr59', 'start': 17, 'end': 21}, {'entity_group': 'B', 'score': 0.73098385, 'word': '= cgmcc', 'start': 26, 'end': 32}, {'entity_group': 'I', 'score': 0.9377573, 'word': '1. 9254', 'start': 33, 'end': 39}, {'entity_group': 'B', 'score': 0.5567825, 'word': '= nbrc', 'start': 43, 'end': 49}, {'entity_group': 'I', 'score': 0.89454174, 'word': '114035', 'start': 50, 'end': 56}]
However, at genome level, strain NA4 shows a higher degree of kinship to type strain CH34 than strain BS1.
[{'entity_group': 'B', 'score': 0.49932447, 'word': 'na4', 'start': 33, 'end': 36}, {'entity_group': 'B', 'score': 0.49380112, 'word': 'ch34', 'start': 85, 'end': 89}, {'entity_group': 'B', 'score': 0.49764434, 'word': 'bs1', 'start': 102, 'end': 105}]
Blochmannia floridanus provides important nutrients for its host, the ant Camponotus, while the bacterium in return is provided with a niche to proliferate.
[]
The dDDH values ranged from 97.7 to 98.0% compared to R. badensis DSM 100043 ^T , and were less than 24.0% when compared to R. silvae 213 ^T , R. chamberiensis 130333 ^T , and R. aceris SAP 1 ^T ( Table 2 ).
[{'entity_group': 'B', 'score': 0.99118304, 'word': 'r', 'start': 54, 'end': 55}, {'entity_group': 'I', 'score': 0.9916577, 'word': '. badensis dsm 100043', 'start': 55, 'end': 76}, {'entity_group': 'B', 'score': 0.9877032, 'word': 'r', 'start': 124, 'end': 125}, {'entity_group': 'I', 'score': 0.9911341, 'word': '. silvae 213', 'start': 125, 'end': 137}, {'entity_group': 'B', 'score': 0.99156815, 'word': 'r', 'start': 143, 'end': 144}, {'entity_group': 'I', 'score': 0.98976445, 'word': '. chamberiensis 130333', 'start': 144, 'end': 166}, {'entity_group': 'B', 'score': 0.98677325, 'word': 'r', 'start': 176, 'end': 177}, {'entity_group': 'I', 'score': 0.9893334, 'word': '. aceris sap 1', 'start': 177, 'end': 191}]
Second, the RAW 264.7 cell line was chosen rather than crude primary cultured macrophages because cell lines provide a more uniform reaction and facilitate the replication of our results by other researchers.
[]
Nitratiruptor was infected multiple times by diverse phages and diversified by the acquisition of prophage genes and various immune mechanisms (phage repressor, restriction modification system, and CRISPR Cas systems).
[]
DobHLH13 and DobHLH16 had the most abundant transcripts in the green root tip with FPKM values of 122.75 and 140.77, respectively.
[]
Coinfection with 5 ethynyl 2′-deoxyuridine (EdU)-labeled HAdV D19 and HAdV D29 was performed in the presence of E. coli K 12 lysate, and the cells were imaged at 12 h postinfection.
[{'entity_group': 'B', 'score': 0.98635685, 'word': 'e', 'start': 112, 'end': 113}, {'entity_group': 'I', 'score': 0.9556439, 'word': '. coli k 12', 'start': 113, 'end': 124}]
Although slightly lower, the corresponding values for NodD _1 structural identity and similarity from B. elkanii strains SEMIA 587, CCBAU 05737, CCBAU 43297 and USDA 94 were 91.61% and 95.97%, respectively.
[{'entity_group': 'B', 'score': 0.5023249, 'word': 'semia', 'start': 121, 'end': 126}, {'entity_group': 'I', 'score': 0.9878081, 'word': '587', 'start': 127, 'end': 130}, {'entity_group': 'I', 'score': 0.7542465, 'word': 'ccbau 05737', 'start': 132, 'end': 143}, {'entity_group': 'I', 'score': 0.77967167, 'word': 'ccbau 43297', 'start': 145, 'end': 156}, {'entity_group': 'B', 'score': 0.51686895, 'word': 'usda', 'start': 161, 'end': 165}, {'entity_group': 'I', 'score': 0.9905404, 'word': '94', 'start': 166, 'end': 168}]
The type stain JJ 42^ T (= LMG 32089^ T = CCM 9085^ T = DSM 111786^ T = CIP 111891^ T) was isolated from the root surface of a field grown corn plant in Dunbar, Nebraska USA.
[{'entity_group': 'I', 'score': 0.74697167, 'word': 'jj 42', 'start': 15, 'end': 20}, {'entity_group': 'B', 'score': 0.7236748, 'word': '= lmg', 'start': 25, 'end': 30}, {'entity_group': 'I', 'score': 0.9669422, 'word': '32089', 'start': 31, 'end': 36}, {'entity_group': 'B', 'score': 0.53712314, 'word': '= ccm', 'start': 40, 'end': 45}, {'entity_group': 'I', 'score': 0.94653344, 'word': '9085', 'start': 46, 'end': 50}, {'entity_group': 'B', 'score': 0.993616, 'word': 'dsm', 'start': 56, 'end': 59}, {'entity_group': 'I', 'score': 0.9551756, 'word': '111786', 'start': 60, 'end': 66}, {'entity_group': 'B', 'score': 0.9928208, 'word': 'cip', 'start': 72, 'end': 75}, {'entity_group': 'I', 'score': 0.9454358, 'word': '111891', 'start': 76, 'end': 82}]
Three bacterial acidophile species were used in this study, L. ferriphilum DSM 14647^T, S. thermosulfidooxidans DSM 9293^T, and A. caldus DSM 8584^T.
[{'entity_group': 'B', 'score': 0.99378633, 'word': 'l', 'start': 60, 'end': 61}, {'entity_group': 'I', 'score': 0.9834545, 'word': '. ferriphilum dsm 14647', 'start': 61, 'end': 84}, {'entity_group': 'B', 'score': 0.9906482, 'word': 's', 'start': 88, 'end': 89}, {'entity_group': 'I', 'score': 0.985803, 'word': '. thermosulfidooxidans dsm 9293', 'start': 89, 'end': 120}, {'entity_group': 'B', 'score': 0.99271613, 'word': 'a', 'start': 128, 'end': 129}, {'entity_group': 'I', 'score': 0.98735493, 'word': '. caldus dsm 8584', 'start': 129, 'end': 146}]
In addition, the mRNA levels of A3H in CEM SS, CEM.NKR, and these cell clones were 100 to 1000 fold lower than those in H9 except that clone #7 expressed slightly higher A3H mRNA (Fig 3C).
[]
Colwellia psychrerythraea 34H was grown in 2216 medium at 10 °C.
[{'entity_group': 'B', 'score': 0.50167197, 'word': 'colwellia', 'start': 0, 'end': 9}, {'entity_group': 'I', 'score': 0.9274828, 'word': 'psychrerythraea 34h', 'start': 10, 'end': 29}]
US 30 had the lowest α amino group content, with the highest surface hydrophobicity, followed by UP 20 (p ≤ 0.05).
[]
Only strain UCD_MED7 (isolated from soymilk) was used for experimentation.
[{'entity_group': 'B', 'score': 0.50730556, 'word': 'ucd', 'start': 12, 'end': 15}, {'entity_group': 'I', 'score': 0.9778507, 'word': '_ med7', 'start': 15, 'end': 20}]
Furthermore, RipAC suppresses the hypersensitive response triggered by avirulence effector RipAA of phylotype I strain GMI1000 ( Nakano et al., 2020 ).
[{'entity_group': 'I', 'score': 0.597126, 'word': 'gmi1000', 'start': 119, 'end': 126}]
Comparative genome sequence analysis revealed that E. coli strain ECU32, in scaffold21xsize74584, carried ORFs for both the ferric enterobactin ABC transporter system ( fepA , fepB , fepC , fepD , fepG , fes ), and enterobactin (siderophore) biosynthesis exporter system ( entB , entC , entD , entE , entF, entS ).
[{'entity_group': 'B', 'score': 0.9923971, 'word': 'e', 'start': 51, 'end': 52}, {'entity_group': 'I', 'score': 0.99106044, 'word': '. coli strain ecu32', 'start': 52, 'end': 71}]
Introduction of tfl1 20 caused a general decrease in leaf number (red arrows in Fig 3G).
[{'entity_group': 'B', 'score': 0.43865675, 'word': 'tfl1', 'start': 16, 'end': 20}, {'entity_group': 'I', 'score': 0.7328387, 'word': '20', 'start': 21, 'end': 23}]
Rice blast disease was reduced by Streptomyces hygroscopicus OsiSh 2 in [14].
[{'entity_group': 'B', 'score': 0.98906404, 'word': 'streptomyces', 'start': 34, 'end': 46}, {'entity_group': 'I', 'score': 0.9876701, 'word': 'hygroscopicus osish 2', 'start': 47, 'end': 68}]
This species also includes Pseudomonas strain CFBP2461, which was isolated from roots of bean in France.
[{'entity_group': 'B', 'score': 0.98880196, 'word': 'pseudomonas', 'start': 27, 'end': 38}, {'entity_group': 'I', 'score': 0.98307824, 'word': 'strain cfbp2461', 'start': 39, 'end': 54}]
The differential occurrence of compensatory mtDNA mutations among strains might explain the relative stability of ΔmtDNA C levels in EG4181 and PB800 compared with the other four strains.
[{'entity_group': 'B', 'score': 0.44834268, 'word': 'eg4181', 'start': 133, 'end': 139}, {'entity_group': 'B', 'score': 0.41740382, 'word': 'pb800', 'start': 144, 'end': 149}]
Here we report the crystal structure of Vps25 at 3.1 Å resolution.
[]
Acrobeloides maximus and Caenorhabditis elegans were grown monoxenically on Escherichia coli S17 1 containing a constitutive red fluorescent protein (RFP) expression plasmid using nutrient free agar plates supplemented with cholesterol at a concentration of 1 µg/ml that is necessary to maintain viable worms [13].
[{'entity_group': 'B', 'score': 0.99275345, 'word': 'escherichia', 'start': 76, 'end': 87}, {'entity_group': 'I', 'score': 0.9866021, 'word': 'coli s17 1', 'start': 88, 'end': 98}]
The HIVconsvX genes were detected in both BCG.HIVconsv1^2auxo.int and BCG.HIVconsv2^2auxo.int strains after 5 weekly subcultures in selective medium without lysine supplementation, as well as two weekly subcultures in lysine supplemented medium (Figure 4A).
[{'entity_group': 'B', 'score': 0.52902067, 'word': 'bcg', 'start': 70, 'end': 73}]
In addition, pre incubation of VHH OMV81 with recombinant CsuA/B inhibited binding to immobilized OMVs derived from 19606 (Fig 3c) and to immobilized recombinant CsuA/B (Fig 3d) in competitive ELISAs.
[]
The phosphate solubilizing P. agglomerans strain ZB isolated from the rhizosphere soil of Araucaria showed a great ability to solubilize different insoluble inorganic phosphate sources through Ca _3 (PO _4 ) _2 (TCP), hydroxyapatite (HP), CaHPO _4 , AlPO _4 , FePO _4 , and rock phosphates (RPs).
[{'entity_group': 'B', 'score': 0.94064814, 'word': 'p', 'start': 27, 'end': 28}, {'entity_group': 'I', 'score': 0.942125, 'word': '. agglomerans strain zb', 'start': 28, 'end': 51}]
[24] For example, it was recently shown that cubic Zr_8O_6 clusters appearing via structure refinements from single crystal X ray diffraction (SCXRD) of PCN 221 actually resulted from the superposition of disordered Zr_6O_4(OH)_4 SBUs
[]
Lines 216 - 224: “We caution though that our immunoassay does not distinguish between poly PG produced from the antisense transcript and poly GP from the sense transcript (Figure 7B).
[]
In addition, the P248L substitution abolished the RDAR colony morphology of FORC_078 and led to the SAW colony morphology similar to that of FORC_075 ( Fig 3b ).
[{'entity_group': 'B', 'score': 0.5823054, 'word': 'forc', 'start': 76, 'end': 80}, {'entity_group': 'I', 'score': 0.92940545, 'word': '_ 078', 'start': 80, 'end': 84}, {'entity_group': 'B', 'score': 0.5746753, 'word': 'forc', 'start': 141, 'end': 145}, {'entity_group': 'I', 'score': 0.9306661, 'word': '_ 075', 'start': 145, 'end': 149}]
DQ12 45 1b was cultured in GPY medium containing glucose 10 g/L, yeast extract 5 g/L, and tryptone 10 g/L at 30 °C.
[{'entity_group': 'B', 'score': 0.49683315, 'word': 'dq12', 'start': 0, 'end': 4}, {'entity_group': 'I', 'score': 0.96027225, 'word': '45 1b', 'start': 5, 'end': 10}]
Moreover, neopeptin A C are identified in S. hygroscopicus NRRL B 1477, S. rimosus NRRL WC387, Streptomyces sp.
[{'entity_group': 'B', 'score': 0.98810345, 'word': 's', 'start': 42, 'end': 43}, {'entity_group': 'I', 'score': 0.98009574, 'word': '. hygroscopicus nrrl b 1477', 'start': 43, 'end': 70}, {'entity_group': 'B', 'score': 0.98881173, 'word': 's', 'start': 72, 'end': 73}, {'entity_group': 'I', 'score': 0.9794307, 'word': '. rimosus nrrl wc387', 'start': 73, 'end': 93}]
Some secreted proteins in phytoplasma, such as SAP54, SAP11, TENGU, SAP05 and Zaofeng 6 were reported [9, 38 41].
[]
On the other hand, the MIC values of the ruthenium compound [Ru(bpy)_2(methionine)]^2+ against the S. aureus MSSA ATCC 25,923 strain and against the E. coli ATCC 11303 strain were of 73.3 and 586.4 µM, respectively (21).
[{'entity_group': 'B', 'score': 0.99351466, 'word': 's', 'start': 99, 'end': 100}, {'entity_group': 'I', 'score': 0.9757938, 'word': '. aureus mssa atcc 25, 923', 'start': 100, 'end': 125}, {'entity_group': 'B', 'score': 0.9944956, 'word': 'e', 'start': 149, 'end': 150}, {'entity_group': 'I', 'score': 0.9862427, 'word': '. coli atcc 11303', 'start': 150, 'end': 167}]
A biochemical and enzymatic study of the purified putative agarases of F. faecale WV33 ^T would elucidate the mechanism of agar depolymerization.
[{'entity_group': 'B', 'score': 0.9913386, 'word': 'f', 'start': 71, 'end': 72}, {'entity_group': 'I', 'score': 0.9909589, 'word': '. faecale wv33', 'start': 72, 'end': 86}]
Liu et al. [16] isolated three indigenous DIRB strains, including Shewanella putrefaciens IAR (iron and As reducing)-S1, Shewanella xiamenensis IR (iron reducing)-S2, and Klebsiella oxytoca IR ZA from the natural groundwater samples of two tube wells of Hangjinhouqi County, China.
[{'entity_group': 'B', 'score': 0.58012974, 'word': 'shewanella', 'start': 66, 'end': 76}, {'entity_group': 'I', 'score': 0.8921032, 'word': 'putrefaciens iar (', 'start': 77, 'end': 95}, {'entity_group': 'B', 'score': 0.72797495, 'word': 's1', 'start': 117, 'end': 119}, {'entity_group': 'B', 'score': 0.5876351, 'word': 'shewanella', 'start': 121, 'end': 131}, {'entity_group': 'I', 'score': 0.94691825, 'word': 'xiamenensis ir (', 'start': 132, 'end': 148}, {'entity_group': 'B', 'score': 0.6029088, 'word': 's2', 'start': 163, 'end': 165}, {'entity_group': 'B', 'score': 0.9936329, 'word': 'klebsiella', 'start': 171, 'end': 181}, {'entity_group': 'I', 'score': 0.9900913, 'word': 'oxytoca ir za', 'start': 182, 'end': 195}]
Similar to other streptococci, S. oriscaviae HKU75 ^T may possess virulence factors that enable it to colonize the oral cavity of guinea pigs and to establish bite wound infection.
[{'entity_group': 'B', 'score': 0.9948002, 'word': 's', 'start': 31, 'end': 32}, {'entity_group': 'I', 'score': 0.99155664, 'word': '. oriscaviae hku75', 'start': 32, 'end': 50}]
The strain 16 SW 7 was isolated from a seawater sample collected near Island Paramushir (Kuril Islands), the Okhotsk Sea, during the 16th cruise of the Research Vessel Academician Oparin by plating 0.1 ml of seawater directly onto nutrient medium as described previously ( Nedashkovskaya et al., 2007 ).
[{'entity_group': 'B', 'score': 0.97485876, 'word': '16', 'start': 11, 'end': 13}, {'entity_group': 'I', 'score': 0.9901158, 'word': 'sw 7', 'start': 14, 'end': 18}]
We previously showed that P. aeruginosa PAO1 induces nuclear localization of DAF 16 as part of the defensive response of animals ( Palominos et al., 2017 ).
[{'entity_group': 'B', 'score': 0.99338657, 'word': 'p', 'start': 26, 'end': 27}, {'entity_group': 'I', 'score': 0.9853123, 'word': '. aeruginosa pao1', 'start': 27, 'end': 44}]
Analysis of the impact of two microbial invaders, the bacterial strain Xanthomonas campestris pv. campestris (Xcc) 8004 and the fungal isolate Alternaria brassicicola (Ab) Abra43 on the structure of seed associated microbial assemblages in Raphanus sativus, indicates the different effect on the endogenous seed microbiota.
[{'entity_group': 'B', 'score': 0.530008, 'word': 'xanthomonas', 'start': 71, 'end': 82}, {'entity_group': 'I', 'score': 0.9543255, 'word': 'campestris pv. campestris (', 'start': 83, 'end': 110}, {'entity_group': 'B', 'score': 0.4927083, 'word': 'xcc', 'start': 110, 'end': 113}, {'entity_group': 'I', 'score': 0.9767013, 'word': ') 8004', 'start': 113, 'end': 119}, {'entity_group': 'B', 'score': 0.52590764, 'word': 'ab', 'start': 168, 'end': 170}, {'entity_group': 'I', 'score': 0.69250447, 'word': ') abra43', 'start': 170, 'end': 178}]
The cell wall peptidoglycan of BG AF3 A ^T contains the amino acids alanine (Ala), glutamic acid (Glu), lysine (Lys), and aspartic acid (Asp), with the molar ratio 1.3 (Ala):0.8 (Asp):1.0 (Glu):1.0 (Lys), suggesting the cell wall peptidoglycan type A4α l -Lys -d -Asp by [ 38 ].
[{'entity_group': 'B', 'score': 0.9888149, 'word': 'bg', 'start': 31, 'end': 33}, {'entity_group': 'I', 'score': 0.98448515, 'word': 'af3 a', 'start': 34, 'end': 39}]
Here, we present draft genome sequences for Dysgonomonas sp. strains GY75 and GY617, isolated from the hindgut of the lower termite Reticulitermes flavipes .
[{'entity_group': 'I', 'score': 0.50560665, 'word': 'gy75', 'start': 69, 'end': 73}, {'entity_group': 'I', 'score': 0.6379986, 'word': 'gy617', 'start': 78, 'end': 83}]
Coincidentally, both V. fujianensis FJ201301 ^T and V. metschnikovii JCM 21189 ^T had 3284 core genes.
[{'entity_group': 'B', 'score': 0.9961021, 'word': 'v', 'start': 21, 'end': 22}, {'entity_group': 'I', 'score': 0.9847314, 'word': '. fujianensis fj201301', 'start': 22, 'end': 44}, {'entity_group': 'B', 'score': 0.99596465, 'word': 'v', 'start': 52, 'end': 53}, {'entity_group': 'I', 'score': 0.98974895, 'word': '. metschnikovii jcm 21189', 'start': 53, 'end': 78}]
The strains “Methylacidiphilum fumariolicum” SolV and “Methylacidiphilum infernorum” V4 possess three complete pmoCAB operons, while “Methylacidiphilum kamchatkense” Kam1 has a fourth distinct copy of pmoA, localized in a truncated pmoCA operon.
[{'entity_group': 'B', 'score': 0.83415335, 'word': '“', 'start': 12, 'end': 13}, {'entity_group': 'I', 'score': 0.75150764, 'word': 'solv', 'start': 45, 'end': 49}, {'entity_group': 'B', 'score': 0.8763543, 'word': '“', 'start': 54, 'end': 55}, {'entity_group': 'I', 'score': 0.66656214, 'word': 'infernorum', 'start': 73, 'end': 83}, {'entity_group': 'I', 'score': 0.8349019, 'word': 'v4', 'start': 85, 'end': 87}, {'entity_group': 'B', 'score': 0.8827546, 'word': '“', 'start': 133, 'end': 134}, {'entity_group': 'I', 'score': 0.53138864, 'word': 'methylacidiphilum kamchatkense', 'start': 134, 'end': 164}, {'entity_group': 'I', 'score': 0.79085076, 'word': 'kam1', 'start': 166, 'end': 170}]
In contrast to the endophytic colonization pattern of Sp245, Sp7, originally isolated from Digitaria in Brazil [ 70 ], is an epiphyte shown to colonize only the surfaces of plant roots such as wheat and corn [ 24 , 26 , 71 ].
[{'entity_group': 'I', 'score': 0.49069515, 'word': 'sp245', 'start': 54, 'end': 59}, {'entity_group': 'B', 'score': 0.49351385, 'word': 'sp7', 'start': 61, 'end': 64}]

In [13]:
predictions = [p for p in predictions if p]

In [14]:
predictions

[[{'entity_group': 'I',
   'score': 0.7429821,
   'word': 'desulfovibrio vulgaris hildenborough',
   'start': 26,
   'end': 62},
  {'entity_group': 'B',
   'score': 0.61041486,
   'word': 'shewanella',
   'start': 186,
   'end': 196},
  {'entity_group': 'I',
   'score': 0.97677726,
   'word': 'oneidensis mr 1',
   'start': 197,
   'end': 212}],
 [{'entity_group': 'B',
   'score': 0.9834554,
   'word': 'b',
   'start': 132,
   'end': 133},
  {'entity_group': 'I',
   'score': 0.9816315,
   'word': '. aryabhattai ab211',
   'start': 133,
   'end': 152}],
 [{'entity_group': 'B',
   'score': 0.9871869,
   'word': 'd',
   'start': 13,
   'end': 14},
  {'entity_group': 'I',
   'score': 0.9762908,
   'word': '. alkenigignens ip3 3',
   'start': 14,
   'end': 35},
  {'entity_group': 'I',
   'score': 0.52383447,
   'word': 't',
   'start': 36,
   'end': 37}],
 [{'entity_group': 'B',
   'score': 0.5020678,
   'word': 'sr59',
   'start': 17,
   'end': 21},
  {'entity_group': 'B',
   'score': 0.73098385,
   'word': '= cgmcc',
   'start': 26,
   'end': 32},
  {'entity_group': 'I',
   'score': 0.9377573,
   'word': '1. 9254',
   'start': 33,
   'end': 39},
  {'entity_group': 'B',
   'score': 0.5567825,
   'word': '= nbrc',
   'start': 43,
   'end': 49},
  {'entity_group': 'I',
   'score': 0.89454174,
   'word': '114035',
   'start': 50,
   'end': 56}],
 [{'entity_group': 'B',
   'score': 0.49932447,
   'word': 'na4',
   'start': 33,
   'end': 36},
  {'entity_group': 'B',
   'score': 0.49380112,
   'word': 'ch34',
   'start': 85,
   'end': 89},
  {'entity_group': 'B',
   'score': 0.49764434,
   'word': 'bs1',
   'start': 102,
   'end': 105}],
 [{'entity_group': 'B',
   'score': 0.99118304,
   'word': 'r',
   'start': 54,
   'end': 55},
  {'entity_group': 'I',
   'score': 0.9916577,
   'word': '. badensis dsm 100043',
   'start': 55,
   'end': 76},
  {'entity_group': 'B',
   'score': 0.9877032,
   'word': 'r',
   'start': 124,
   'end': 125},
  {'entity_group': 'I',
   'score': 0.9911341,
   'word': '. silvae 213',
   'start': 125,
   'end': 137},
  {'entity_group': 'B',
   'score': 0.99156815,
   'word': 'r',
   'start': 143,
   'end': 144},
  {'entity_group': 'I',
   'score': 0.98976445,
   'word': '. chamberiensis 130333',
   'start': 144,
   'end': 166},
  {'entity_group': 'B',
   'score': 0.98677325,
   'word': 'r',
   'start': 176,
   'end': 177},
  {'entity_group': 'I',
   'score': 0.9893334,
   'word': '. aceris sap 1',
   'start': 177,
   'end': 191}],
 [{'entity_group': 'B',
   'score': 0.98635685,
   'word': 'e',
   'start': 112,
   'end': 113},
  {'entity_group': 'I',
   'score': 0.9556439,
   'word': '. coli k 12',
   'start': 113,
   'end': 124}],
 [{'entity_group': 'B',
   'score': 0.5023249,
   'word': 'semia',
   'start': 121,
   'end': 126},
  {'entity_group': 'I',
   'score': 0.9878081,
   'word': '587',
   'start': 127,
   'end': 130},
  {'entity_group': 'I',
   'score': 0.7542465,
   'word': 'ccbau 05737',
   'start': 132,
   'end': 143},
  {'entity_group': 'I',
   'score': 0.77967167,
   'word': 'ccbau 43297',
   'start': 145,
   'end': 156},
  {'entity_group': 'B',
   'score': 0.51686895,
   'word': 'usda',
   'start': 161,
   'end': 165},
  {'entity_group': 'I',
   'score': 0.9905404,
   'word': '94',
   'start': 166,
   'end': 168}],
 [{'entity_group': 'I',
   'score': 0.74697167,
   'word': 'jj 42',
   'start': 15,
   'end': 20},
  {'entity_group': 'B',
   'score': 0.7236748,
   'word': '= lmg',
   'start': 25,
   'end': 30},
  {'entity_group': 'I',
   'score': 0.9669422,
   'word': '32089',
   'start': 31,
   'end': 36},
  {'entity_group': 'B',
   'score': 0.53712314,
   'word': '= ccm',
   'start': 40,
   'end': 45},
  {'entity_group': 'I',
   'score': 0.94653344,
   'word': '9085',
   'start': 46,
   'end': 50},
  {'entity_group': 'B',
   'score': 0.993616,
   'word': 'dsm',
   'start': 56,
   'end': 59},
  {'entity_group': 'I',
   'score': 0.9551756,
   'word': '111786',
   'start': 60,
   'end': 66},
  {'entity_group': 'B',
   'score': 0.9928208,
   'word': 'cip',
   'start': 72,
   'end': 75},
  {'entity_group': 'I',
   'score': 0.9454358,
   'word': '111891',
   'start': 76,
   'end': 82}],
 [{'entity_group': 'B',
   'score': 0.99378633,
   'word': 'l',
   'start': 60,
   'end': 61},
  {'entity_group': 'I',
   'score': 0.9834545,
   'word': '. ferriphilum dsm 14647',
   'start': 61,
   'end': 84},
  {'entity_group': 'B',
   'score': 0.9906482,
   'word': 's',
   'start': 88,
   'end': 89},
  {'entity_group': 'I',
   'score': 0.985803,
   'word': '. thermosulfidooxidans dsm 9293',
   'start': 89,
   'end': 120},
  {'entity_group': 'B',
   'score': 0.99271613,
   'word': 'a',
   'start': 128,
   'end': 129},
  {'entity_group': 'I',
   'score': 0.98735493,
   'word': '. caldus dsm 8584',
   'start': 129,
   'end': 146}],
 [{'entity_group': 'B',
   'score': 0.50167197,
   'word': 'colwellia',
   'start': 0,
   'end': 9},
  {'entity_group': 'I',
   'score': 0.9274828,
   'word': 'psychrerythraea 34h',
   'start': 10,
   'end': 29}],
 [{'entity_group': 'B',
   'score': 0.50730556,
   'word': 'ucd',
   'start': 12,
   'end': 15},
  {'entity_group': 'I',
   'score': 0.9778507,
   'word': '_ med7',
   'start': 15,
   'end': 20}],
 [{'entity_group': 'I',
   'score': 0.597126,
   'word': 'gmi1000',
   'start': 119,
   'end': 126}],
 [{'entity_group': 'B',
   'score': 0.9923971,
   'word': 'e',
   'start': 51,
   'end': 52},
  {'entity_group': 'I',
   'score': 0.99106044,
   'word': '. coli strain ecu32',
   'start': 52,
   'end': 71}],
 [{'entity_group': 'B',
   'score': 0.43865675,
   'word': 'tfl1',
   'start': 16,
   'end': 20},
  {'entity_group': 'I',
   'score': 0.7328387,
   'word': '20',
   'start': 21,
   'end': 23}],
 [{'entity_group': 'B',
   'score': 0.98906404,
   'word': 'streptomyces',
   'start': 34,
   'end': 46},
  {'entity_group': 'I',
   'score': 0.9876701,
   'word': 'hygroscopicus osish 2',
   'start': 47,
   'end': 68}],
 [{'entity_group': 'B',
   'score': 0.98880196,
   'word': 'pseudomonas',
   'start': 27,
   'end': 38},
  {'entity_group': 'I',
   'score': 0.98307824,
   'word': 'strain cfbp2461',
   'start': 39,
   'end': 54}],
 [{'entity_group': 'B',
   'score': 0.44834268,
   'word': 'eg4181',
   'start': 133,
   'end': 139},
  {'entity_group': 'B',
   'score': 0.41740382,
   'word': 'pb800',
   'start': 144,
   'end': 149}],
 [{'entity_group': 'B',
   'score': 0.99275345,
   'word': 'escherichia',
   'start': 76,
   'end': 87},
  {'entity_group': 'I',
   'score': 0.9866021,
   'word': 'coli s17 1',
   'start': 88,
   'end': 98}],
 [{'entity_group': 'B',
   'score': 0.52902067,
   'word': 'bcg',
   'start': 70,
   'end': 73}],
 [{'entity_group': 'B',
   'score': 0.94064814,
   'word': 'p',
   'start': 27,
   'end': 28},
  {'entity_group': 'I',
   'score': 0.942125,
   'word': '. agglomerans strain zb',
   'start': 28,
   'end': 51}],
 [{'entity_group': 'B',
   'score': 0.5823054,
   'word': 'forc',
   'start': 76,
   'end': 80},
  {'entity_group': 'I',
   'score': 0.92940545,
   'word': '_ 078',
   'start': 80,
   'end': 84},
  {'entity_group': 'B',
   'score': 0.5746753,
   'word': 'forc',
   'start': 141,
   'end': 145},
  {'entity_group': 'I',
   'score': 0.9306661,
   'word': '_ 075',
   'start': 145,
   'end': 149}],
 [{'entity_group': 'B',
   'score': 0.49683315,
   'word': 'dq12',
   'start': 0,
   'end': 4},
  {'entity_group': 'I',
   'score': 0.96027225,
   'word': '45 1b',
   'start': 5,
   'end': 10}],
 [{'entity_group': 'B',
   'score': 0.98810345,
   'word': 's',
   'start': 42,
   'end': 43},
  {'entity_group': 'I',
   'score': 0.98009574,
   'word': '. hygroscopicus nrrl b 1477',
   'start': 43,
   'end': 70},
  {'entity_group': 'B',
   'score': 0.98881173,
   'word': 's',
   'start': 72,
   'end': 73},
  {'entity_group': 'I',
   'score': 0.9794307,
   'word': '. rimosus nrrl wc387',
   'start': 73,
   'end': 93}],
 [{'entity_group': 'B',
   'score': 0.99351466,
   'word': 's',
   'start': 99,
   'end': 100},
  {'entity_group': 'I',
   'score': 0.9757938,
   'word': '. aureus mssa atcc 25, 923',
   'start': 100,
   'end': 125},
  {'entity_group': 'B',
   'score': 0.9944956,
   'word': 'e',
   'start': 149,
   'end': 150},
  {'entity_group': 'I',
   'score': 0.9862427,
   'word': '. coli atcc 11303',
   'start': 150,
   'end': 167}],
 [{'entity_group': 'B',
   'score': 0.9913386,
   'word': 'f',
   'start': 71,
   'end': 72},
  {'entity_group': 'I',
   'score': 0.9909589,
   'word': '. faecale wv33',
   'start': 72,
   'end': 86}],
 [{'entity_group': 'B',
   'score': 0.58012974,
   'word': 'shewanella',
   'start': 66,
   'end': 76},
  {'entity_group': 'I',
   'score': 0.8921032,
   'word': 'putrefaciens iar (',
   'start': 77,
   'end': 95},
  {'entity_group': 'B',
   'score': 0.72797495,
   'word': 's1',
   'start': 117,
   'end': 119},
  {'entity_group': 'B',
   'score': 0.5876351,
   'word': 'shewanella',
   'start': 121,
   'end': 131},
  {'entity_group': 'I',
   'score': 0.94691825,
   'word': 'xiamenensis ir (',
   'start': 132,
   'end': 148},
  {'entity_group': 'B',
   'score': 0.6029088,
   'word': 's2',
   'start': 163,
   'end': 165},
  {'entity_group': 'B',
   'score': 0.9936329,
   'word': 'klebsiella',
   'start': 171,
   'end': 181},
  {'entity_group': 'I',
   'score': 0.9900913,
   'word': 'oxytoca ir za',
   'start': 182,
   'end': 195}],
 [{'entity_group': 'B',
   'score': 0.9948002,
   'word': 's',
   'start': 31,
   'end': 32},
  {'entity_group': 'I',
   'score': 0.99155664,
   'word': '. oriscaviae hku75',
   'start': 32,
   'end': 50}],
 [{'entity_group': 'B',
   'score': 0.97485876,
   'word': '16',
   'start': 11,
   'end': 13},
  {'entity_group': 'I',
   'score': 0.9901158,
   'word': 'sw 7',
   'start': 14,
   'end': 18}],
 [{'entity_group': 'B',
   'score': 0.99338657,
   'word': 'p',
   'start': 26,
   'end': 27},
  {'entity_group': 'I',
   'score': 0.9853123,
   'word': '. aeruginosa pao1',
   'start': 27,
   'end': 44}],
 [{'entity_group': 'B',
   'score': 0.530008,
   'word': 'xanthomonas',
   'start': 71,
   'end': 82},
  {'entity_group': 'I',
   'score': 0.9543255,
   'word': 'campestris pv. campestris (',
   'start': 83,
   'end': 110},
  {'entity_group': 'B',
   'score': 0.4927083,
   'word': 'xcc',
   'start': 110,
   'end': 113},
  {'entity_group': 'I',
   'score': 0.9767013,
   'word': ') 8004',
   'start': 113,
   'end': 119},
  {'entity_group': 'B',
   'score': 0.52590764,
   'word': 'ab',
   'start': 168,
   'end': 170},
  {'entity_group': 'I',
   'score': 0.69250447,
   'word': ') abra43',
   'start': 170,
   'end': 178}],
 [{'entity_group': 'B',
   'score': 0.9888149,
   'word': 'bg',
   'start': 31,
   'end': 33},
  {'entity_group': 'I',
   'score': 0.98448515,
   'word': 'af3 a',
   'start': 34,
   'end': 39}],
 [{'entity_group': 'I',
   'score': 0.50560665,
   'word': 'gy75',
   'start': 69,
   'end': 73},
  {'entity_group': 'I',
   'score': 0.6379986,
   'word': 'gy617',
   'start': 78,
   'end': 83}],
 [{'entity_group': 'B',
   'score': 0.9961021,
   'word': 'v',
   'start': 21,
   'end': 22},
  {'entity_group': 'I',
   'score': 0.9847314,
   'word': '. fujianensis fj201301',
   'start': 22,
   'end': 44},
  {'entity_group': 'B',
   'score': 0.99596465,
   'word': 'v',
   'start': 52,
   'end': 53},
  {'entity_group': 'I',
   'score': 0.98974895,
   'word': '. metschnikovii jcm 21189',
   'start': 53,
   'end': 78}],
 [{'entity_group': 'B',
   'score': 0.83415335,
   'word': '“',
   'start': 12,
   'end': 13},
  {'entity_group': 'I',
   'score': 0.75150764,
   'word': 'solv',
   'start': 45,
   'end': 49},
  {'entity_group': 'B',
   'score': 0.8763543,
   'word': '“',
   'start': 54,
   'end': 55},
  {'entity_group': 'I',
   'score': 0.66656214,
   'word': 'infernorum',
   'start': 73,
   'end': 83},
  {'entity_group': 'I',
   'score': 0.8349019,
   'word': 'v4',
   'start': 85,
   'end': 87},
  {'entity_group': 'B',
   'score': 0.8827546,
   'word': '“',
   'start': 133,
   'end': 134},
  {'entity_group': 'I',
   'score': 0.53138864,
   'word': 'methylacidiphilum kamchatkense',
   'start': 134,
   'end': 164},
  {'entity_group': 'I',
   'score': 0.79085076,
   'word': 'kam1',
   'start': 166,
   'end': 170}],
 [{'entity_group': 'I',
   'score': 0.49069515,
   'word': 'sp245',
   'start': 54,
   'end': 59},
  {'entity_group': 'B',
   'score': 0.49351385,
   'word': 'sp7',
   'start': 61,
   'end': 64}],
 [{'entity_group': 'B', 'score': 0.9955446, 'word': 'e', 'start': 0, 'end': 1},
  {'entity_group': 'I',
   'score': 0.9754962,
   'word': '. coli cect 504',
   'start': 1,
   'end': 16}],
 [{'entity_group': 'B',
   'score': 0.5101111,
   'word': 'usda',
   'start': 149,
   'end': 153},
  {'entity_group': 'I',
   'score': 0.9813147,
   'word': '94',
   'start': 154,
   'end': 156},
  {'entity_group': 'B',
   'score': 0.5458846,
   'word': 'usda',
   'start': 158,
   'end': 162},
  {'entity_group': 'I',
   'score': 0.9143921,
   'word': '3254',
   'start': 163,
   'end': 167},
  {'entity_group': 'B',
   'score': 0.54186344,
   'word': 'usda',
   'start': 173,
   'end': 177},
  {'entity_group': 'I',
   'score': 0.8992982,
   'word': '3259',
   'start': 178,
   'end': 182}],
 [{'entity_group': 'B',
   'score': 0.47230363,
   'word': 'nitrospira',
   'start': 143,
   'end': 153},
  {'entity_group': 'I',
   'score': 0.9372945,
   'word': 'moscoviensis m 1',
   'start': 154,
   'end': 170}],
 [{'entity_group': 'B',
   'score': 0.7292647,
   'word': 'citrobacter',
   'start': 75,
   'end': 86},
  {'entity_group': 'I',
   'score': 0.9930808,
   'word': 'werkmanii strain wwn1',
   'start': 87,
   'end': 108},
  {'entity_group': 'B',
   'score': 0.9954827,
   'word': 'enterobacter',
   'start': 113,
   'end': 125},
  {'entity_group': 'I',
   'score': 0.994169,
   'word': 'cloacae strain jwm6',
   'start': 126,
   'end': 145}],
 [{'entity_group': 'B',
   'score': 0.9690484,
   'word': 'salmonella',
   'start': 0,
   'end': 10},
  {'entity_group': 'I',
   'score': 0.948646,
   'word': 'enterica serotype braenderup',
   'start': 11,
   'end': 39},
  {'entity_group': 'I',
   'score': 0.42117962,
   'word': 'h9812',
   'start': 41,
   'end': 46}],
 [{'entity_group': 'I',
   'score': 0.64868116,
   'word': '. fumigatus cea10',
   'start': 182,
   'end': 199}],
 [{'entity_group': 'B',
   'score': 0.9956132,
   'word': 'l',
   'start': 74,
   'end': 75},
  {'entity_group': 'I',
   'score': 0.9841222,
   'word': '. paracasei fam18149',
   'start': 75,
   'end': 95}],
 [{'entity_group': 'B',
   'score': 0.8518856,
   'word': 't',
   'start': 72,
   'end': 73},
  {'entity_group': 'I',
   'score': 0.9087552,
   'word': '. harzianum cect 2413',
   'start': 73,
   'end': 94}],
 [{'entity_group': 'B',
   'score': 0.60974586,
   'word': 'sulfurovum',
   'start': 111,
   'end': 121},
  {'entity_group': 'I',
   'score': 0.65511477,
   'word': 'sp000296775',
   'start': 122,
   'end': 133}],
 [{'entity_group': 'I',
   'score': 0.90533507,
   'word': 'bradyrhizobium sp. strain wsm1743',
   'start': 0,
   'end': 33}],
 [{'entity_group': 'I',
   'score': 0.6566532,
   'word': 'wh131',
   'start': 56,
   'end': 61},
  {'entity_group': 'I',
   'score': 0.6562625,
   'word': 'wh158',
   'start': 68,
   'end': 73}],
 [{'entity_group': 'I',
   'score': 0.43786994,
   'word': 'sk678',
   'start': 12,
   'end': 17}],
 [{'entity_group': 'B',
   'score': 0.44229624,
   'word': 'inbov1',
   'start': 61,
   'end': 67}],
 [{'entity_group': 'B', 'score': 0.9916415, 'word': 'l', 'start': 0, 'end': 1},
  {'entity_group': 'I',
   'score': 0.9826237,
   'word': '. plantarum strain mf1298',
   'start': 1,
   'end': 26}],
 [{'entity_group': 'I',
   'score': 0.6149605,
   'word': 'sbw25',
   'start': 40,
   'end': 45}],
 [{'entity_group': 'B',
   'score': 0.5057694,
   'word': 'sybc',
   'start': 4,
   'end': 8},
  {'entity_group': 'I',
   'score': 0.9872931,
   'word': 'h47',
   'start': 9,
   'end': 12}],
 [{'entity_group': 'B',
   'score': 0.9924395,
   'word': 'escherichia',
   'start': 83,
   'end': 94},
  {'entity_group': 'I',
   'score': 0.9899042,
   'word': 'coli k 12',
   'start': 95,
   'end': 104}],
 [{'entity_group': 'B',
   'score': 0.45697638,
   'word': 'am1',
   'start': 42,
   'end': 45}],
 [{'entity_group': 'B',
   'score': 0.99476045,
   'word': 'v',
   'start': 30,
   'end': 31},
  {'entity_group': 'I',
   'score': 0.9823851,
   'word': '. fujianensis fj201301',
   'start': 31,
   'end': 53}],
 [{'entity_group': 'I',
   'score': 0.60013366,
   'word': '19',
   'start': 17,
   'end': 19}],
 [{'entity_group': 'B',
   'score': 0.98294306,
   'word': 'pseudomonas',
   'start': 74,
   'end': 85},
  {'entity_group': 'I',
   'score': 0.97783667,
   'word': 'mendocina lyx',
   'start': 86,
   'end': 99}],
 [{'entity_group': 'B',
   'score': 0.9336767,
   'word': 'staphylococcus',
   'start': 0,
   'end': 14},
  {'entity_group': 'I',
   'score': 0.9511272,
   'word': 'chromogenes ta',
   'start': 15,
   'end': 29}],
 [{'entity_group': 'B',
   'score': 0.99111813,
   'word': 'b',
   'start': 73,
   'end': 74},
  {'entity_group': 'I',
   'score': 0.9896404,
   'word': '. melitensis 16m',
   'start': 74,
   'end': 90},
  {'entity_group': 'B',
   'score': 0.9920048,
   'word': 'b',
   'start': 126,
   'end': 127},
  {'entity_group': 'I',
   'score': 0.98859864,
   'word': '. suis 1330',
   'start': 127,
   'end': 138}],
 [{'entity_group': 'B',
   'score': 0.57400334,
   'word': 'pseudomonas',
   'start': 0,
   'end': 11},
  {'entity_group': 'I',
   'score': 0.6951318,
   'word': 'aeruginosa',
   'start': 12,
   'end': 22},
  {'entity_group': 'I',
   'score': 0.816933,
   'word': '10265',
   'start': 30,
   'end': 35}],
 [{'entity_group': 'B',
   'score': 0.9951485,
   'word': 'p',
   'start': 42,
   'end': 43},
  {'entity_group': 'I',
   'score': 0.9898429,
   'word': '. luminescens him3',
   'start': 43,
   'end': 61},
  {'entity_group': 'B',
   'score': 0.9952676,
   'word': 'p',
   'start': 73,
   'end': 74},
  {'entity_group': 'I',
   'score': 0.9898584,
   'word': '. aeruginosa na04',
   'start': 74,
   'end': 91}],
 [{'entity_group': 'I',
   'score': 0.82887703,
   'word': 'bradyrhizobium elkanii usda61',
   'start': 0,
   'end': 29}],
 [{'entity_group': 'B',
   'score': 0.4949854,
   'word': 't81',
   'start': 0,
   'end': 3}],
 [{'entity_group': 'B',
   'score': 0.41113365,
   'word': 'bgsp7',
   'start': 120,
   'end': 125},
  {'entity_group': 'B',
   'score': 0.42578104,
   'word': 'bgsp9',
   'start': 127,
   'end': 132},
  {'entity_group': 'B',
   'score': 0.42491126,
   'word': 'bgsp11',
   'start': 137,
   'end': 143}],
 [{'entity_group': 'I',
   'score': 0.52358073,
   'word': 's',
   'start': 50,
   'end': 51},
  {'entity_group': 'B',
   'score': 0.9865123,
   'word': 'escherichia',
   'start': 57,
   'end': 68},
  {'entity_group': 'I',
   'score': 0.98819566,
   'word': 'coli k12',
   'start': 69,
   'end': 77}],
 [{'entity_group': 'I',
   'score': 0.47413793,
   'word': 'mrs07',
   'start': 154,
   'end': 159},
  {'entity_group': 'I',
   'score': 0.594167,
   'word': '52',
   'start': 160,
   'end': 162}],
 [{'entity_group': 'B',
   'score': 0.8709286,
   'word': 'ch',
   'start': 214,
   'end': 216},
  {'entity_group': 'B',
   'score': 0.8598256,
   'word': 'ch',
   'start': 221,
   'end': 223},
  {'entity_group': 'B',
   'score': 0.8464146,
   'word': 'ch',
   'start': 228,
   'end': 230}],
 [{'entity_group': 'B',
   'score': 0.9402429,
   'word': 'e',
   'start': 205,
   'end': 206},
  {'entity_group': 'I',
   'score': 0.91345465,
   'word': '. coli o157 : h7',
   'start': 206,
   'end': 220}],
 [{'entity_group': 'B',
   'score': 0.9945306,
   'word': 'e',
   'start': 31,
   'end': 32},
  {'entity_group': 'I',
   'score': 0.99109393,
   'word': '. coli mg1655',
   'start': 32,
   'end': 45},
  {'entity_group': 'I',
   'score': 0.43738145,
   'word': 'atcc700926',
   'start': 47,
   'end': 57},
  {'entity_group': 'B',
   'score': 0.99431854,

In [15]:
for prediction in predictions:
    pred = prediction[0]["word"]
    count = 0
    pred = pred.replace(" - ","-").replace("- ","-").replace(" -","-")
    for annotation in annotations:
        ann = annotation["text"]
        ann = ann.lower()
        if ann in pred:
            count +=1
    if count ==0:
        print(pred)

b
d
r
e
semia
jj 42
l
colwellia
ucd
e
tfl1
streptomyces
pseudomonas
eg4181
escherichia
p
forc
dq12
s
s
f
shewanella
s
16
p
xanthomonas
bg
v
“
e
usda
nitrospira
citrobacter
salmonella
. fumigatus cea10
l
t
sulfurovum
wh131
l
sybc
escherichia
v
19
pseudomonas
staphylococcus
b
pseudomonas
p
s
mrs07
ch
e
e
k
ucd
wf
b
p
l
b
dq12
p
pseudomonas
ccug
c
l
p
_ palustris _ 1
coli
enteroscipio
arcobacter
bacillus
pseudomonas
nctc
v
h
a
delftia
c
um
e
m
l
e
dhe
b
forc
bacillus
resag
v
s
b
p
bacillus
e
1
r
b
dq12
citrobacter
6
c
psychromonas
lactobacillus
h
s
k
dechloromonas
chlorobium
ard6
e
e
e
se188
l
nta1
7
v
ors
3b
staphylococcus
vibrio
bb22op
s
salmonella
citrobacter
p
n3
s
parvum 4 14
l
anabaena
0385m 1
chryseobacterium
klebsiella
streptomyces
pseudomonas
b
firmicutes
e
bacillus
s
citrobacter
hibernicus bz 3 1
b
enterobacter
c
b
v
r
vibrio
bacillus
n
cc
k
mob
e
e
escherichia
mbo
osish
wf
lg1d9
c
atcc
ppo70 4
mycobacterium
sbm 03
p
dechloromonas
60
dsm
citrobacter
b
ka5
neau
lrs4. 154
cfbp
lactococcus
mbo
escherichia
agrobacterium
flavobacterium
forc
cect
lactobacillus
lactobacillus
staphylococcus
e
m
l
s
b
forc
pcc
f
ecu32
b
16
st7
escherichia
pseudomonas
h
2015aw
pseudomonas
var
b
haemolytica serotype a2
flavobacterium
p
16
v
b
cc
b
burkholderia
mtb
c
e
bacillus
synechococcus
o3
p
phaseolibacter flectensatcc 12775
g

In [14]:
merged

,tokens,ner_tags,id,predictions,label_ids,word_ids,ner
0,"[We, also, found, 20, nonribosomally, synthesi...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",0,"[[-2.956822395324707, -3.364196300506592, 7.22...","[-100, 2, 2, 2, 2, 2, -100, -100, -100, 2, 2, ...","[None, 0, 1, 2, 3, 4, 4, 4, 4, 5, 6, 7, 8, 9, ...",ISOLATE
1,"[The, isobutanol, biosynthesis, pathway, in, S...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",1,"[[-2.948723077774048, -3.370908737182617, 7.29...","[-100, 2, 2, -100, -100, 2, 2, 2, 2, -100, 2, ...","[None, 0, 1, 1, 1, 2, 3, 4, 5, 5, 6, 6, 6, 7, ...",ISOLATE
2,"[Strain, ME23, specifically, was, identified, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O]",2,"[[-2.8552932739257812, -3.23327374458313, 6.88...","[-100, 2, 2, -100, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[None, 0, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11...",ISOLATE
3,"[BRCA2, tumours, expressed, cyclin, D1, and, D...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",3,"[[-2.735277652740478, -3.456892967224121, 7.22...","[-100, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1...",ISOLATE
4,"[One, contained, 12, of, the, 14, milk, strain...","[O, O, O, O, O, O, B, O, O, O, O, O, O, O, O, ...",4,"[[-2.889482736587524, -3.250913143157959, 7.06...","[-100, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, ...","[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1...",ISOLATE
...,...,...,...,...,...,...,...
775,"[Being, on, the, inclusion, membrane, ,, CT006...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",775,"[[-2.911547183990478, -3.356550693511963, 7.33...","[-100, 2, 2, 2, 2, 2, 2, 2, -100, -100, 2, 2, ...","[None, 0, 1, 2, 3, 4, 5, 6, 6, 6, 7, 8, 9, 10,...",ISOLATE
776,"[Based, on, the, results, of, AZCL, screening,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",776,"[[-2.804240465164184, -3.308460235595703, 7.10...","[-100, 2, 2, 2, 2, 2, 2, -100, 2, 2, 2, 2, 2, ...","[None, 0, 1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 10...",ISOLATE
777,"[Meanwhile, ,, different, ICEs, have, been, de...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",777,"[[-2.845585346221924, -3.365410089492798, 7.31...","[-100, 2, 2, 2, 2, -100, 2, 2, 2, 2, 2, -100, ...","[None, 0, 1, 2, 3, 3, 4, 5, 6, 7, 8, 8, 9, 9, ...",ISOLATE
778,"[This, might, benefit, from, the, symbiosis, r...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",778,"[[-2.865844011306762, -3.423704624176025, 7.28...","[-100, 2, 2, 2, 2, 2, 2, 2, 2, 2, -100, -100, ...","[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8, 9, ...",ISOLATE
779,"[Moreover, ,, CcMan5C, had, more, negatively, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",779,"[[-2.847104549407959, -3.4378621578216553, 7.3...","[-100, 2, 2, 2, -100, -100, -100, 2, 2, 2, 2, ...","[None, 0, 1, 2, 2, 2, 2, 3, 4, 5, 6, 7, 8, 9, ...",ISOLATE

In [15]:
merged

,tokens,ner_tags,id,predictions,label_ids,word_ids,ner
0,"[We, also, found, 20, nonribosomally, synthesi...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",0,"[[-2.956822395324707, -3.364196300506592, 7.22...","[-100, 2, 2, 2, 2, 2, -100, -100, -100, 2, 2, ...","[None, 0, 1, 2, 3, 4, 4, 4, 4, 5, 6, 7, 8, 9, ...",ISOLATE
1,"[The, isobutanol, biosynthesis, pathway, in, S...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",1,"[[-2.948723077774048, -3.370908737182617, 7.29...","[-100, 2, 2, -100, -100, 2, 2, 2, 2, -100, 2, ...","[None, 0, 1, 1, 1, 2, 3, 4, 5, 5, 6, 6, 6, 7, ...",ISOLATE
2,"[Strain, ME23, specifically, was, identified, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O]",2,"[[-2.8552932739257812, -3.23327374458313, 6.88...","[-100, 2, 2, -100, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[None, 0, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11...",ISOLATE
3,"[BRCA2, tumours, expressed, cyclin, D1, and, D...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",3,"[[-2.735277652740478, -3.456892967224121, 7.22...","[-100, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1...",ISOLATE
4,"[One, contained, 12, of, the, 14, milk, strain...","[O, O, O, O, O, O, B, O, O, O, O, O, O, O, O, ...",4,"[[-2.889482736587524, -3.250913143157959, 7.06...","[-100, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, ...","[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1...",ISOLATE
...,...,...,...,...,...,...,...
775,"[Being, on, the, inclusion, membrane, ,, CT006...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",775,"[[-2.911547183990478, -3.356550693511963, 7.33...","[-100, 2, 2, 2, 2, 2, 2, 2, -100, -100, 2, 2, ...","[None, 0, 1, 2, 3, 4, 5, 6, 6, 6, 7, 8, 9, 10,...",ISOLATE
776,"[Based, on, the, results, of, AZCL, screening,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",776,"[[-2.804240465164184, -3.308460235595703, 7.10...","[-100, 2, 2, 2, 2, 2, 2, -100, 2, 2, 2, 2, 2, ...","[None, 0, 1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 10...",ISOLATE
777,"[Meanwhile, ,, different, ICEs, have, been, de...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",777,"[[-2.845585346221924, -3.365410089492798, 7.31...","[-100, 2, 2, 2, 2, -100, 2, 2, 2, 2, 2, -100, ...","[None, 0, 1, 2, 3, 3, 4, 5, 6, 7, 8, 8, 9, 9, ...",ISOLATE
778,"[This, might, benefit, from, the, symbiosis, r...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",778,"[[-2.865844011306762, -3.423704624176025, 7.28...","[-100, 2, 2, 2, 2, 2, 2, 2, 2, 2, -100, -100, ...","[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8, 9, ...",ISOLATE
779,"[Moreover, ,, CcMan5C, had, more, negatively, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",779,"[[-2.847104549407959, -3.4378621578216553, 7.3...","[-100, 2, 2, 2, -100, -100, -100, 2, 2, 2, 2, ...","[None, 0, 1, 2, 2, 2, 2, 3, 4, 5, 6, 7, 8, 9, ...",ISOLATE

In [16]:
## TODO: also split the annotations by "-"
# Create an empty dataframe to store the results
results_df = pd.DataFrame(columns=['NER', 'Prediction'])

ners = ["STRAIN", "METABOLITE", "SPECIES", "ISOLATE", "COMPOUND","MEDIUM", "ORGANISM", "PHENOTYPE", "PROTEIN","MORPHOLOGY","EFFECT","DISEASE"]

for ner in ners:
    test_sentences = pd.read_json(f"../NER/{ner}/test.json", lines=True)
    test_output = pd.read_json(f"../NER_output/{ner}/test_outputs.json")
    merged = pd.merge(test_sentences, test_output, left_index=True, right_index=True)
    merged.loc[:, "ner"] = ner

    annotations = []
    current_annotation = None

    for j in range(len(merged)):
        for i in zip(merged.loc[j, "tokens"], merged.loc[j, "ner_tags"]):
            if i[1] != "O":
                if current_annotation is None:
                    current_annotation = {"text": i[0]}
                else:
                    current_annotation["text"] += " " + i[0]
            else:
                if current_annotation is not None:
                    annotations.append(current_annotation)
                    current_annotation = None

    if current_annotation is not None:
        annotations.append(current_annotation)

    path = f"../NER_output/{ner}"

    tokenizer = AutoTokenizer.from_pretrained(path, model_max_length=512)
    model = AutoModelForTokenClassification.from_pretrained(path)

    nlp = pipeline(task='ner', model=model, tokenizer=tokenizer,
                   aggregation_strategy="average", device=0)

    # Specify the path to the JSONL file
    jsonl_file = f"../NER/{ner}/test.jsonls"

    predictions = []
    # Open the JSONL file
    with jsonlines.open(jsonl_file) as reader:
        # Iterate over each line in the file
        for line in reader:
            for l in line:

                # Get the value from the "text" field
                text = l["data"]["text"]
                # Pass the value to the nlp() function
                predict = nlp(text)
                predictions.append(predict)
    predictions = [p for p in predictions if p]

    # Store the predictions in the dataframe
    for prediction in predictions:
        pred = prediction[0]["word"]
        count = 0
        pred = pred.replace(" - ", "-").replace("- ", "-").replace(" -", "-").lower()
        for annotation in annotations:
            ann = annotation["text"]
            ann = ann.lower()
            if ann in pred:
                count += 1
        if count == 0:
            results_df = pd.concat([results_df, pd.DataFrame({'NER': [ner], 'Prediction': [pred]})], ignore_index=True)

    annotations_set = [i["text"].lower().split(" ") for i in annotations]
    annotations_set = set(itertools.chain.from_iterable(annotations_set))

    predictions_set = [i[0]["word"].lower().replace(" - ", "-").replace("- ", "-").replace(" -", "-").split(" ") for i in predictions]
    predictions_set = set(itertools.chain.from_iterable(predictions_set))

    ann_not_pred = annotations_set.difference(predictions_set)
    pred_not_ann = predictions_set.difference(annotations_set)

    # with open(f"ner_annotation/{ner}_ann_not_pred.txt", "w") as f:
    #     for i in ann_not_pred:
    #         f.write(i + "\n")
    with open(f"ner_annotation/{ner}_pred_not_ann.txt", "w") as f:
        for i in pred_not_ann:
            f.write(i + "\n")

/home/gomez/miniconda3/envs/torch/lib/python3.11/site-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/home/gomez/miniconda3/envs/torch/lib/python3.11/site-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/home/gomez/miniconda3/envs/torch/lib/python3.11/site-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/home/gomez/miniconda3/envs/torch/lib/python3.11/site-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/home/gomez/miniconda3/envs/torch/lib/python3.11/site-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/home/gomez/miniconda3/envs/torch/lib/python3.11/site-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/home/gomez/miniconda3/envs/torch/lib/python3.11/site-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/home/gomez/miniconda3/envs/torch/lib/python3.11/site-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/home/gomez/miniconda3/envs/torch/lib/python3.11/site-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/home/gomez/miniconda3/envs/torch/lib/python3.11/site-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/home/gomez/miniconda3/envs/torch/lib/python3.11/site-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/home/gomez/miniconda3/envs/torch/lib/python3.11/site-packages/transformers/pipelines/base.py:1090: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(